{
  "name": "babel-plugin-async-AutomaticallyAddCatch",
  "version": "1.0.0",
  "description": "a babel plugin that captures error of async function",
  "main": "lib/index.js",
  "scripts": {
    "lib": "rm -rf lib && npx babel src -d lib --presets=@babel/preset-env",
    "test": "npm run lib && node ./test/test.js",
    "prepublishOnly": "npm run lib"
  },
  "dependencies": {
    "@babel/core": "^7.0.0",
    "@babel/cli": "^7.0.0",
    "@babel/preset-env": "^7.0.0"
  },
  "keywords": [
    "try",
    "catch",
    "babel",
    "plugin"
  ],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "glob": "^7.1.6"
  }
}
